################################################################################
# @Project - WES Hair Follicle
# @Date - 02/03/2026
# @Author - Yoav Avi-Guy
# @Description - This file extracts the sequencing quality control data from the 
# json files generated by ODCF and merges them to a dataframe
################################################################################

#-------------------------------------------------------------------------------
# SOURCE
source(file.path(Sys.getenv("HF_SCC_ROOT", unset = "."), "WES/01_source/00_config.r"))

#-------------------------------------------------------------------------------
# Libraries
  library(purrr)
  library(readr)
  library(stringr)
  library(tibble)
  library(jsonlite)

#-------------------------------------------------------------------------------
# Paths
QC_PATH <- Sys.getenv("HF_SCC_WES_QC_ROOT")
if (!nzchar(QC_PATH)) stop("Set HF_SCC_WES_QC_ROOT to the WES QC input directory.")
bam_project_prefix <- Sys.getenv("HF_SCC_WES_BAM_PROJECT_PREFIX")
if (!nzchar(bam_project_prefix)) {
  stop("Set HF_SCC_WES_BAM_PROJECT_PREFIX to the WES BAM project prefix.")
}

#-------------------------------------------------------------------------------
# Loading work files
samples <- read_lines(
  file.path(INPUT_PATH, "/samples.txt"))
sample_metadata <- readRDS(
  file.path(METADATA_PATH, "sample_metadata.rds"))
mutations_annotated <- readRDS(
  file.path(PROCESSED_PATH, "mutations_annotated.rds"))

#-------------------------------------------------------------------------------
# Helper functions

sample_paths <- function(sample) {

  qc_dir <- Sys.glob(file.path(
    QC_PATH, "*", sample,
    "paired/merged-alignment/qualitycontrol/merged"
  ))

  if (length(qc_dir) != 1) {
    stop(
      sprintf(
        "ERROR: expected exactly 1 QC directory for sample '%s' across all PIDs; found %d",
        sample, length(qc_dir)
      ),
      call. = FALSE
    )
  }

  flag_glob <- Sys.glob(file.path(
    qc_dir,
    "flagstats",
    paste0(sample, "_", bam_project_prefix,
      "*_merged.mdup.bam_extendedFlagstats.txt")
  ))

  if (length(flag_glob) != 1) {
    stop(
      sprintf(
        "ERROR: expected exactly 1 flagstats file for sample '%s' across all PIDs; found %d",
        sample, length(flag_glob)
      ),
      call. = FALSE
    )
  }

  list(
    qc_json  = file.path(qc_dir, "qualitycontrol.json"),
    tgt_json = file.path(qc_dir, "qualitycontrol_targetExtract.json"),
    flag_txt = flag_glob[[1]])
}

## Read summary QC fields from json files
read_all_from_qc <- function(path) {
  js <- read_json(path, simplifyVector = FALSE)
  all_node <- js[["all"]]
  as_tibble_row(all_node)
}

## Read relevant summary QC fields from target json files
read_target_fields <- function(path) {
  js <- read_json(path, simplifyVector = FALSE)
  all_node <- js[["all"]]
  tibble(
    target_qcBasesMapped = 
      as.numeric(all_node$qcBasesMapped %||% NA_real_),
    target_genomeWithoutNCoverageQcBases = 
      as.numeric(all_node$genomeWithoutNCoverageQcBases %||% NA_real_))
}

## Read non-duplicate mapped reads from flagstats
read_non_duplicate_mapped_reads <- function(path) {
  x <- read_lines(path)
  line <- x[stringr::str_detect(x, "such with mapping quality >=\\s*1")][1]
  nums <- stringr::str_extract_all(line, "\\d+")[[1]]
  as.integer(tail(nums, 1))
}

#-------------------------------------------------------------------------------
# Building the dataframe
qc_summary <- map_dfr(samples, function(smp) {
  p <- sample_paths(smp)

  qc_row <- read_all_from_qc(p$qc_json)

  tgt_row <- read_target_fields(p$tgt_json)

  flag_row <- tibble(
    non_duplicate_mapped_reads = read_non_duplicate_mapped_reads(p$flag_txt))

  bind_cols(tibble(sample_name = smp), qc_row, tgt_row, flag_row)}) %>%
  mutate(
    duplicate_pct = 100 * duplicates / totalReadCounter,
    mapped_pct = 100 * totalMappedReadCounter / totalReadCounter,
    paired_pct = 100 * properlyPaired / totalReadCounter,
    on_target_ratio = target_qcBasesMapped / qcBasesMapped,
    unique_pct = 100 * non_duplicate_mapped_reads / totalReadCounter 
  ) %>%
  rename(coverage = target_genomeWithoutNCoverageQcBases)

#-------------------------------------------------------------------------------
# Adding metadata annotation to sequencing stats for downstream analysis. When 
# the columns overlap, keeping only the columns from the sample metadata
overlap <- intersect(
  names(qc_summary),
  setdiff(names(sample_metadata), 
  "sample_name"))

qc_summary_annotated <- qc_summary %>%
  select(-all_of(overlap)) %>%
  left_join(sample_metadata, by = "sample_name") %>%
  filter(tissue %in% c("Hair follicle", "Skin"))

#-------------------------------------------------------------------------------
# Adding coverage and deduplicated read count per sample to the mutations
# and metadata dataframes
mutations_annotated <- mutations_annotated %>%
  left_join(
    qc_summary %>%
    transmute(
      sample_name,
      coverage,
      reads = non_duplicate_mapped_reads),
      by = "sample_name")

sample_metadata <- sample_metadata %>%
  left_join(
    qc_summary %>%
    transmute(
      sample_name,
      coverage,
      reads = non_duplicate_mapped_reads),
      by = "sample_name")

#-------------------------------------------------------------------------------
# Saving qc summary df
saveRDS(qc_summary_annotated,
file.path(PROCESSED_PATH, "/seq_qc_summary.rds"))

# Saving mutations and metadta dataframes
saveRDS(mutations_annotated,
file.path(PROCESSED_PATH, "/mutations_annotated.rds"))

saveRDS(sample_metadata,
file.path(METADATA_PATH, "/sample_metadata.rds"))

#-------------------------------------------------------------------------------
# session info
capture.output(sessionInfo(),
  file = file.path(SESSION_INFO_PATH, "06_seq_qc_session.txt"))
