################################################################################
# @Project - TES Hair Follicle
# @Date - 22/01/2026
# @Author - Yoav Avi-Guy
# @Description - This file extracts the sequencing quality control data from the 
# json files generated by ODCF and merges them to a dataframe
################################################################################

#-------------------------------------------------------------------------------
# SOURCE
source(file.path(Sys.getenv("HF_SCC_ROOT", unset = "."), "TES/01_source/00_config.r"))

#-------------------------------------------------------------------------------
# Libraries
  library(purrr)
  library(readr)
  library(stringr)
  library(tibble)
  library(jsonlite)

#-------------------------------------------------------------------------------
# Paths
QC_PATH <- Sys.getenv("HF_SCC_TES_QC_ROOT")
if (!nzchar(QC_PATH)) stop("Set HF_SCC_TES_QC_ROOT to the TES QC input directory.")
bam_suffix <- Sys.getenv("HF_SCC_TES_BAM_SUFFIX")
if (!nzchar(bam_suffix)) stop("Set HF_SCC_TES_BAM_SUFFIX to the TES BAM filename suffix.")

#-------------------------------------------------------------------------------
# Loading the declared sample manifest
samples <- read_lines(
  file.path(INPUT_PATH, "/samples.txt"))

#-------------------------------------------------------------------------------
# Helper functions

sample_paths <- function(sample) {
    QC_PATH <- file.path(
      QC_PATH, sample, 
      "paired/merged-alignment/qualitycontrol/merged")
  list(
    qc_json    = file.path(
      QC_PATH, 
      "qualitycontrol.json"),
    tgt_json   = file.path(
      QC_PATH, 
      "qualitycontrol_targetExtract.json"),
    flag_txt   = file.path(
      QC_PATH, "flagstats",
      paste0(
        sample, 
        bam_suffix, "_extendedFlagstats.txt")))
}

## Read summary QC fields from json files
read_all_from_qc <- function(path) {
  js <- read_json(path, simplifyVector = FALSE)
  all_node <- js[["all"]]
  as_tibble_row(all_node)
}

## Read relevant summary QC fields from target json files
read_target_fields <- function(path) {
  js <- read_json(path, simplifyVector = FALSE)
  all_node <- js[["all"]]
  tibble(
    target_qcBasesMapped = 
      as.numeric(all_node$qcBasesMapped %||% NA_real_),
    target_genomeWithoutNCoverageQcBases = 
      as.numeric(all_node$genomeWithoutNCoverageQcBases %||% NA_real_))
}

## Read non-duplicate mapped reads from flagstats
read_non_duplicate_mapped_reads <- function(path) {
  x <- read_lines(path)
  line <- x[stringr::str_detect(x, "such with mapping quality >=\\s*1")][1]
  nums <- stringr::str_extract_all(line, "\\d+")[[1]]
  as.integer(tail(nums, 1))
}

#-------------------------------------------------------------------------------
# Building the dataframe
qc_summary <- map_dfr(samples, function(smp) {
  p <- sample_paths(smp)

  qc_row <- read_all_from_qc(p$qc_json)

  tgt_row <- read_target_fields(p$tgt_json)

  flag_row <- tibble(
    non_duplicate_mapped_reads = read_non_duplicate_mapped_reads(p$flag_txt))

  bind_cols(tibble(sample_name = smp), qc_row, tgt_row, flag_row)}) %>%
  mutate(
    duplicate_pct = 100 * duplicates / totalReadCounter,
    mapped_pct = 100 * totalMappedReadCounter / totalReadCounter,
    paired_pct = 100 * properlyPaired / totalReadCounter,
    on_target_ratio = target_qcBasesMapped / qcBasesMapped,
    unique_pct = 100 * non_duplicate_mapped_reads / totalReadCounter 
  ) %>%
  rename(coverage = target_genomeWithoutNCoverageQcBases)

#-------------------------------------------------------------------------------
# Saving the metadata-independent technical QC source
saveRDS(qc_summary,
  file.path(PROCESSED_PATH, "/seq_qc_technical.rds"))

#-------------------------------------------------------------------------------
# session info
capture.output(sessionInfo(),
  file = file.path(SESSION_INFO_PATH, "08_seq_qc_session.txt"))
